id: AD229432A
title: 'MSV 3,01: Bhikṣuṇīvibhaṅga'
type: translation
pechas:
- IB0D6D0A8
source_metadata:
  languages:
  - bo
  datatype: PlainText
  created_at: 2023-02-10 00:08:24.599864
  last_modified_at: 2023-02-10 00:08:24.599877
alignment_to_base:
  IB0D6D0A8/15AC: 0DDB
